### ISSUE TITLE
docs: Update file path in Readme.md

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FlutterUIKit#3]
# Issue 🦠

Under screenshots section we provide links to users, so that they can easily access the code to a specific page. The codebase has now been upgraded but the links are still pointing to the old files, which do not exist at the moment. In this task, we want to update the link to the files.

## Reference ⬆

![image](https://github.com/AmanNegi/FlutterUIKit/assets/37607224/4abacbc5-c9c9-4371-9d96-b2154812f743)

## Example 🐲

```md
FROM: 
https://github.com/AmanNegi/FlutterUIKit/blob/main/lib/pages/auth/login_page.dart

TO:
https://github.com/AmanNegi/FlutterUIKit/blob/main/src/lib/pages/auth/login_page.dart
```

**Comment by prajapatihet** [comment]
I think there is problem in package declaration
Check also files once

**Comment by AmanNegi** [comment]
> I think there is problem in package declaration Check also files once

Didn't got what you wanted to say. Can you add references, for better understanding?
