### ISSUE TITLE
[docs] Update Contributing Section

### ISSUE THREAD

**Issue by AmanNegi** [AmanNegi/FlutterUIKit#5]
# Description

In `Readme.md` we have a section of `https://github.com/AmanNegi/FlutterUIKit#-contributing` however, we separately store the `CONTRIBUTING.md` in the `docs` folder. 

In this task, we require to remove the Contributing guidelines from `README.md` and simply add a text saying that "Want to contribute to FlutterUIKit? Check out contributing guidelines" which should link to the `docs\CONTRIBUTING.md`.

**Comment by segunojo1** [comment]
Hello please assign me

**Comment by AmanNegi** [comment]
Fixed via #6
